name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.19
      uses: actions/setup-go@v5
      with:
        go-version: 1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        version: '~> v2'
        args: --snapshot --skip publish --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Windows 64-bit
        path: dist/packwiz_windows_amd64_v1/

#    - name: Upload assets
#      uses: actions/upload-artifact@v4
#      with:
#        name: Windows 32-bit
#        path: dist/packwiz_windows_386/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Windows 64-bit ARM
        path: dist/packwiz_windows_arm64/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux 64-bit x86
        path: dist/packwiz_linux_amd64_v1/

#    - name: Upload assets
#      uses: actions/upload-artifact@v4
#      with:
#        name: Linux 32-bit x86
#        path: dist/packwiz_linux_386/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: Linux 64-bit ARM
        path: dist/packwiz_linux_arm64/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: macOS 64-bit x86
        path: dist/packwiz_darwin_amd64_v1/

    - name: Upload assets
      uses: actions/upload-artifact@v4
      with:
        name: macOS 64-bit ARM
        path: dist/packwiz_darwin_arm64/